CREATE TABLE IF NOT EXISTS "polls" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"maci" text NOT NULL,
	"address" text NOT NULL,
	"poll_id" text NOT NULL,
	"start_date" text NOT NULL,
	"end_date" text NOT NULL,
	"poll_public_key_x" text NOT NULL,
	"poll_public_key_y" text NOT NULL,
	"created_at_ms" bigint NOT NULL
);
