packages:
  - "circuits"
  - "apps/*"
  - "scripts/*"
overrides:
  "@expo/log-box": "57.0.4"
  "@expo/ui": "57.0.20"
  "expo": "57.0.25"
  "expo-constants": "57.0.19"
  "expo-font": "57.0.4"
  "expo-modules-core": "57.0.19"
  "expo-router": "57.0.23"
allowBuilds:
  "@parcel/watcher": true
  blake-hash: true
  esbuild: true
  unrs-resolver: true
