// Curve: A*x^2 + y^2 = 1 + D*x^2*y^2
//
// BabyJubJub is represented over the Cairo field modulus Q.
//
// The implementation uses extended Edwards coordinates internally:
//
//   affine:
//     x = X / Z
//     y = Y / Z
//
//   extended:
//     T = X*Y/Z
//
// The extended-coordinate invariant is therefore:
//
//   X*Y = Z*T
//
// This representation allows point addition and doubling to be
// performed without field inversion. A single inversion is performed
// when converting the final point back to affine coordinates.
pub mod BabyJubJub {
    use crate::utils::math::math;

    /// Edwards curve coefficient A.
    pub const A: u256 = 0x292FC; // 168700

    /// Edwards curve coefficient D.
    pub const D: u256 = 0x292F8; // 168696

    /// Base field modulus.
    pub const Q: u256 =
        0x30644E72E131A029B85045B68181585D2833E84879B9709143E1F593F0000001;

    /// Order of the prime-order subgroup generated by `GENERATOR`.
    pub const SUBGROUP_ORDER: u256 =
        0x060c89ce5c263405370a08b6d0302b0bab3eedb83920ee0a677297dc392126f1;

    /// Generator of the BabyJubJub prime-order subgroup.
    pub const GENERATOR: (u256, u256) = (
        5299619240641551281634865583518297030282874472190772894086521144482721001553,
        16950150798460657717958625567821834550301663161624707787222815936182638968203,
    );

    /// A BabyJubJub point in extended Edwards coordinates.
    ///
    /// The corresponding affine coordinates are:
    ///
    ///   x = X / Z
    ///   y = Y / Z
    ///
    /// and `t` stores:
    ///
    ///   T = X*Y/Z
    ///
    /// Consequently, every valid extended point satisfies:
    ///
    ///   X*Y = Z*T
    ///
    /// All coordinates are represented modulo `Q`.
    #[derive(Copy, Drop)]
    pub struct Point {
        pub x: u256,
        pub y: u256,
        pub z: u256,
        pub t: u256,
    }

    /// Returns the identity element of the elliptic-curve group.
    ///
    /// In affine coordinates the identity is:
    ///
    ///   (0, 1)
    ///
    /// Its extended-coordinate representation is:
    ///
    ///   (0, 1, 1, 0)
    pub fn identity() -> Point {
        Point { x: 0, y: 1, z: 1, t: 0 }
    }

    /// Converts an affine point `(x, y)` into extended coordinates.
    ///
    /// Since `Z = 1`, the extended `T` coordinate is:
    ///
    ///   T = X*Y
    ///
    /// computed modulo `Q`.
    pub fn from_affine(x: u256, y: u256) -> Point {
        Point { x: x, y: y, z: 1, t: math::mul_mod(x, y, Q) }
    }

    /// Converts an extended-coordinate point back to affine coordinates.
    ///
    /// This operation requires one modular inversion:
    ///
    ///   x = X/Z
    ///   y = Y/Z
    ///
    /// Point addition and doubling intentionally avoid inversion; the
    /// inversion is deferred until the final conversion to affine form.
    ///
    /// The identity is handled explicitly because its representation
    /// has `x = 0` and `y = z`.
    pub fn to_affine(p: Point) -> (u256, u256) {
        if p.x == 0 && p.y == p.z {
            return (0, 1);
        }

        let z_inv = inverse(p.z);

        let x = math::mul_mod(p.x, z_inv, Q);
        let y = math::mul_mod(p.y, z_inv, Q);

        (x, y)
    }

    /// Adds two points represented in extended Edwards coordinates.
    ///
    /// The formula is implemented entirely with modular additions,
    /// subtractions, and multiplications. No field inversion is required.
    ///
    /// Given points `P` and `Q`, the intermediate values correspond to
    /// the standard extended Edwards addition formula for the curve:
    ///
    ///   A*x^2 + y^2 = 1 + D*x^2*y^2
    ///
    /// The returned point remains in extended coordinates and satisfies
    /// the invariant `X*Y = Z*T`.
    pub fn add_extended(p: Point, q: Point) -> Point {
        let a = math::mul_mod(p.x, q.x, Q);
        let b = math::mul_mod(p.y, q.y, Q);

        let t1t2 = math::mul_mod(p.t, q.t, Q);
        let c = math::mul_mod(D, t1t2, Q);

        let d = math::mul_mod(p.z, q.z, Q);

        let x1_plus_y1 = math::add_mod(p.x, p.y, Q);
        let x2_plus_y2 = math::add_mod(q.x, q.y, Q);

        let e0 = math::mul_mod(x1_plus_y1, x2_plus_y2, Q);

        let e1 = math::sub_mod(e0, a, Q);
        let e = math::sub_mod(e1, b, Q);

        let f = math::sub_mod(d, c, Q);
        let g = math::add_mod(d, c, Q);

        let a_times_a = math::mul_mod(A, a, Q);
        let h = math::sub_mod(b, a_times_a, Q);

        let x3 = math::mul_mod(e, f, Q);
        let y3 = math::mul_mod(g, h, Q);
        let t3 = math::mul_mod(e, h, Q);
        let z3 = math::mul_mod(f, g, Q);

        Point { x: x3, y: y3, z: z3, t: t3 }
    }

    /// Doubles a point in extended Edwards coordinates.
    ///
    /// Like `add_extended`, this operation performs no field inversion.
    /// The result is returned in extended coordinates and can therefore
    /// be chained with further additions or doublings without converting
    /// back to affine coordinates.
    pub fn double_extended(p: Point) -> Point {
        let a = math::mul_mod(p.x, p.x, Q);
        let b = math::mul_mod(p.y, p.y, Q);

        let z_squared = math::mul_mod(p.z, p.z, Q);
        let two_z_squared = math::add_mod(z_squared, z_squared, Q);

        let a_curve = math::mul_mod(A, a, Q);
        let x_plus_y = math::add_mod(p.x, p.y, Q);
        let x_plus_y_squared = math::mul_mod(x_plus_y, x_plus_y, Q);

        let e1 = math::sub_mod(x_plus_y_squared, a, Q);
        let e = math::sub_mod(e1, b, Q);
        let g = math::add_mod(a_curve, b, Q);
        let f = math::sub_mod(g, two_z_squared, Q);
        let h = math::sub_mod(a_curve, b, Q);

        let x3 = math::mul_mod(e, f, Q);
        let y3 = math::mul_mod(g, h, Q);
        let t3 = math::mul_mod(e, h, Q);
        let z3 = math::mul_mod(f, g, Q);

        Point { x: x3, y: y3, z: z3, t: t3 }
    }

    /// Computes the scalar multiple `s * P`.
    ///
    /// The scalar multiplication uses the binary double-and-add method.
    /// The point is kept in extended coordinates throughout the loop so
    /// that no modular inversion is performed for intermediate points.
    ///
    /// The final result is converted back to affine coordinates, requiring
    /// exactly one modular inversion.
    ///
    /// `s` is interpreted as an unsigned scalar. When `s == 0`, the
    /// identity point `(0, 1)` is returned.
    pub fn mul(x: u256, y: u256, s: u256) -> (u256, u256) {
        let mut remaining = s;

        let mut result = identity();
        let mut base = from_affine(x, y);

        while remaining != 0 {
            if remaining % 2 != 0 {
                result = add_extended(result, base);
            }

            remaining /= 2;

            if remaining != 0 {
                base = double_extended(base);
            }
        }

        to_affine(result)
    }

    /// Computes the multiplicative inverse of `a` modulo `Q`.
    ///
    /// For non-zero `a` in the prime field, Fermat's little theorem gives:
    ///
    ///   a^(-1) = a^(Q-2) mod Q
    ///
    /// The function rejects zero because zero has no multiplicative inverse.
    pub fn inverse(a: u256) -> u256 {
        let a = a % Q;

        assert!(a != 0);

        math::pow_mod(a, Q - 2, Q)
    }

    /// Returns the additive inverse of the x-coordinate.
    ///
    /// For an Edwards point `(x, y)`, negation is:
    ///
    ///   (-x, y)
    ///
    /// where `-x` is computed modulo `Q`.
    ///
    /// The zero coordinate is kept as zero rather than represented as `Q`.
    pub fn negate(x: u256, y: u256) -> (u256, u256) {
        let neg_x = if x == 0 {
            0
        } else {
            Q - x % Q
        };

        (neg_x, y)
    }

    /// Adds two affine BabyJubJub points.
    ///
    /// The points are temporarily converted to extended coordinates,
    /// added using `add_extended`, and converted back to affine form.
    ///
    /// Because the conversion back to affine coordinates requires an
    /// inversion, this wrapper performs one modular inversion.
    pub fn add(x1: u256, y1: u256, x2: u256, y2: u256) -> (u256, u256) {
        let p = from_affine(x1, y1);
        let q = from_affine(x2, y2);

        let result = add_extended(p, q);

        to_affine(result)
    }

    /// Doubles an affine BabyJubJub point.
    ///
    /// The point is converted to extended coordinates, doubled without
    /// inversion, and then converted back to affine coordinates.
    pub fn double(x: u256, y: u256) -> (u256, u256) {
        let p = from_affine(x, y);

        let result = double_extended(p);

        to_affine(result)
    }

    /// Checks whether an affine point lies on the BabyJubJub curve.
    ///
    /// A point `(x, y)` is on the curve when:
    ///
    ///   A*x^2 + y^2 = 1 + D*x^2*y^2  (mod Q)
    ///
    /// The comparison is performed entirely in the field and therefore
    /// does not require any modular inversion.
    ///
    /// This function checks curve membership only. It does not by itself
    /// prove that the point belongs to the prime-order subgroup generated
    /// by `GENERATOR`.
    pub fn is_on_curve(x: u256, y: u256) -> bool {
        let xsq = math::mul_mod(x, x, Q);
        let ysq = math::mul_mod(y, y, Q);

        let lhs = math::add_mod(math::mul_mod(A, xsq, Q), ysq, Q);

        let rhs = math::add_mod(
            1,
            math::mul_mod(math::mul_mod(D, xsq, Q), ysq, Q),
            Q
        );

        math::sub_mod(lhs, rhs, Q) == 0
    }
}
